[project]
name = "FMDV_immune_dynamics"
authors = [
    {name = "Jan Medlock", email = "medlockj@oregonstate.edu"},
    {name = "et alia"},
]
maintainers = [
    {name = "Jan Medlock", email = "medlockj@oregonstate.edu"},
]
readme = "README.md"
license = {text = "AGPL-3.0-only"}
license-files = ["LICENSE"]
dynamic = ["version"]
requires-python = "==3.13.*"
dependencies = [
    # Simulation core
    "numpy==2.2.4",
    "scipy==1.15.3",
    "sortedcontainers==2.4.0",
    "pandas==2.2.3", # +dfsg
    "tables==3.10.2",
    "joblib==1.4.2",
    "psutil==7.0.0",
    # Plotting and other post-processing
    "matplotlib==3.10.1", # +dfsg1
    "seaborn==0.13.2",
    "statsmodels==0.14.5", # +dfsg
    "astropy==7.1.0",
]

[project.optional-dependencies]
# Speed finding initial conditions in 'herd/initial_conditions/immune_status'
cython = ["cython==3.0.11"]
# Notebook in 'test/'
jupyter = ["notebook==6.4.13"]

[project.urls]
Repository = "https://github.com/janmedlock/FMDV_immune_dynamics.git"

[tool.pdm]
distribution = false

[tool.pdm.version]
source = "scm"
