* Save multiple tables in '*.h5' files, one for each script
  Drop as much from 'h5.py' as possible, although setting the defaults
  for compression etc seems still useful.

* Save less output, calculate and saved derived output at the end of each run
  + Only 'simulation_plot.py' uses the raw simulation data:
    stop saving it for the other scripts.
  + Only 'acute_plot.py', 'baseline_plot.py', and
    'susceptibility_null_plot.py' use '*_infected.py':
    stop saving it for other scripts.
    + 'susceptibility_null_plot.py' reads from
      'susceptibility_infected.h5': make it run directly.
  + No plotting script uses '*_downsampled.h5':
    Either stop saving it or '*_infected.h5'.
  + I think dask is then no longer needed: remove it.

* Improve initializing time since entry
  At equilibrium, the distribution of times since entry has
  probability density S(z) / mu, where S(z) is the survival function
  and mu is the mean waiting time. Sample from
  that. `herd.event.Event.sample_time()` will need a flag to
  distinguish between initialing the simulation using the sampling
  process above and the sampling there now for a buffalo entering a
  new state (which is only different for events with time since entry,
  i.e. not exponential random variables).
  Maternal-immunity waning is in this same category.

* Old
** Investigate the 26 samples that break
  `herd.initial_conditions.immune_state.solve()`
** Compare `susceptibility_null` to old model
** Write up: `herd.initial_conditions.immune_status.Solver.get_pdf()` now
   sets `pdf[0] = 0`
*** How does `(hazard_infection, newborn_proportion_immune)` in
    `herd.initial_conditions.immune_status.Solver.solve()` change as
    `pdf[0]` varies?

* Merge changes in devel branch
  + Consider renaming columns by copying, then
    + Merge devel into main
    + Hide 'todo.org' in main
    + Push to github

  + Delete 'devel' directory
